export const airports = [
  // --- EUROPE ---
  { value: "LIS", label: "Lisboa (LIS), Portugal" },
  { value: "OPO", label: "Porto (OPO), Portugal" },
  { value: "FAO", label: "Faro (FAO), Portugal" },
  { value: "FNC", label: "Funchal (FNC), Portugal" },
  { value: "PDL", label: "Ponta Delgada (PDL), Portugal" },
  { value: "TER", label: "Terceira (TER), Portugal" },
  { value: "HOR", label: "Horta (HOR), Portugal" },
  { value: "PXO", label: "Porto Santo (PXO), Portugal" },
  { value: "MAD", label: "Madrid (MAD), Espanha" },
  { value: "BCN", label: "Barcelona (BCN), Espanha" },
  { value: "AGP", label: "Málaga (AGP), Espanha" },
  { value: "VLC", label: "Valência (VLC), Espanha" },
  { value: "BIO", label: "Bilbau (BIO), Espanha" },
  { value: "SVQ", label: "Sevilha (SVQ), Espanha" },
  { value: "PMI", label: "Palma de Maiorca (PMI), Espanha" },
  { value: "LHR", label: "Londres Heathrow (LHR), Reino Unido" },
  { value: "LGW", label: "Londres Gatwick (LGW), Reino Unido" },
  { value: "STN", label: "Londres Stansted (STN), Reino Unido" },
  { value: "LTN", label: "Londres Luton (LTN), Reino Unido" },
  { value: "MAN", label: "Manchester (MAN), Reino Unido" },
  { value: "EDI", label: "Edimburgo (EDI), Reino Unido" },
  { value: "GLA", label: "Glasgow (GLA), Reino Unido" },
  { value: "CDG", label: "Paris Charles de Gaulle (CDG), França" },
  { value: "ORY", label: "Paris Orly (ORY), França" },
  { value: "NCE", label: "Nice (NCE), França" },
  { value: "LYS", label: "Lyon (LYS), França" },
  { value: "MRS", label: "Marselha (MRS), França" },
  { value: "AMS", label: "Amesterdão (AMS), Países Baixos" },
  { value: "RTM", label: "Roterdão (RTM), Países Baixos" },
  { value: "FRA", label: "Frankfurt (FRA), Alemanha" },
  { value: "MUC", label: "Munique (MUC), Alemanha" },
  { value: "BER", label: "Berlim (BER), Alemanha" },
  { value: "HAM", label: "Hamburgo (HAM), Alemanha" },
  { value: "DUS", label: "Dusseldorf (DUS), Alemanha" },
  { value: "FCO", label: "Roma Fiumicino (FCO), Itália" },
  { value: "MXP", label: "Milão Malpensa (MXP), Itália" },
  { value: "LIN", label: "Milão Linate (LIN), Itália" },
  { value: "VCE", label: "Veneza (VCE), Itália" },
  { value: "BLQ", label: "Bolonha (BLQ), Itália" },
  { value: "NAP", label: "Nápoles (NAP), Itália" },
  { value: "ZRH", label: "Zurique (ZRH), Suíça" },
  { value: "GVA", label: "Genebra (GVA), Suíça" },
  { value: "BSL", label: "Basileia (BSL), Suíça" },
  { value: "VIE", label: "Viena (VIE), Áustria" },
  { value: "BRU", label: "Bruxelas (BRU), Bélgica" },
  { value: "CRL", label: "Charleroi (CRL), Bélgica" },
  { value: "DUB", label: "Dublin (DUB), Irlanda" },
  { value: "CPH", label: "Copenhaga (CPH), Dinamarca" },
  { value: "OSL", label: "Oslo (OSL), Noruega" },
  { value: "ARN", label: "Estocolmo (ARN), Suécia" },
  { value: "HEL", label: "Helsínquia (HEL), Finlândia" },
  { value: "WAW", label: "Varsóvia (WAW), Polónia" },
  { value: "KRK", label: "Cracóvia (KRK), Polónia" },
  { value: "PRG", label: "Praga (PRG), República Checa" },
  { value: "BUD", label: "Budapeste (BUD), Hungria" },
  { value: "ATH", label: "Atenas (ATH), Grécia" },
  { value: "SKG", label: "Salónica (SKG), Grécia" },
  { value: "IST", label: "Istambul (IST), Turquia" },
  { value: "SAW", label: "Istambul Sabiha Gokcen (SAW), Turquia" },
  { value: "AYT", label: "Antália (AYT), Turquia" },
  { value: "SVO", label: "Moscovo Sheremetyevo (SVO), Rússia" },
  { value: "DME", label: "Moscovo Domodedovo (DME), Rússia" },
  { value: "LED", label: "São Petersburgo (LED), Rússia" },
  { value: "KBP", label: "Kiev (KBP), Ucrânia" },
  { value: "OTP", label: "Bucareste (OTP), Roménia" },
  { value: "SOF", label: "Sófia (SOF), Bulgária" },
  { value: "BEG", label: "Belgrado (BEG), Sérvia" },
  { value: "ZAG", label: "Zagreb (ZAG), Croácia" },
  { value: "DBV", label: "Dubrovnik (DBV), Croácia" },
  { value: "SPU", label: "Split (SPU), Croácia" },
  { value: "LJU", label: "Liubliana (LJU), Eslovénia" },
  { value: "MLA", label: "Malta (MLA), Malta" },
  { value: "LCA", label: "Larnaca (LCA), Chipre" },
  { value: "KEF", label: "Reiquiavique (KEF), Islândia" },

  // --- NORTH AMERICA ---
  { value: "JFK", label: "Nova Iorque JFK (JFK), EUA" },
  { value: "EWR", label: "Nova Iorque Newark (EWR), EUA" },
  { value: "LGA", label: "Nova Iorque LaGuardia (LGA), EUA" },
  { value: "LAX", label: "Los Angeles (LAX), EUA" },
  { value: "SFO", label: "São Francisco (SFO), EUA" },
  { value: "MIA", label: "Miami (MIA), EUA" },
  { value: "MCO", label: "Orlando (MCO), EUA" },
  { value: "ORD", label: "Chicago O'Hare (ORD), EUA" },
  { value: "ATL", label: "Atlanta (ATL), EUA" },
  { value: "DFW", label: "Dallas Fort Worth (DFW), EUA" },
  { value: "DEN", label: "Denver (DEN), EUA" },
  { value: "SEA", label: "Seattle (SEA), EUA" },
  { value: "LAS", label: "Las Vegas (LAS), EUA" },
  { value: "BOS", label: "Boston (BOS), EUA" },
  { value: "IAD", label: "Washington Dulles (IAD), EUA" },
  { value: "YYZ", label: "Toronto Pearson (YYZ), Canadá" },
  { value: "YVR", label: "Vancouver (YVR), Canadá" },
  { value: "YUL", label: "Montreal (YUL), Canadá" },
  { value: "YYC", label: "Calgary (YYC), Canadá" },
  { value: "MEX", label: "Cidade do México (MEX), México" },
  { value: "CUN", label: "Cancún (CUN), México" },
  { value: "GDL", label: "Guadalajara (GDL), México" },

  // --- SOUTH & CENTRAL AMERICA ---
  { value: "GRU", label: "São Paulo Guarulhos (GRU), Brasil" },
  { value: "GIG", label: "Rio de Janeiro Galeão (GIG), Brasil" },
  { value: "BSB", label: "Brasília (BSB), Brasil" },
  { value: "CNF", label: "Belo Horizonte (CNF), Brasil" },
  { value: "SSA", label: "Salvador (SSA), Brasil" },
  { value: "REC", label: "Recife (REC), Brasil" },
  { value: "FOR", label: "Fortaleza (FOR), Brasil" },
  { value: "EZE", label: "Buenos Aires Ezeiza (EZE), Argentina" },
  { value: "AEP", label: "Buenos Aires Aeroparque (AEP), Argentina" },
  { value: "SCL", label: "Santiago (SCL), Chile" },
  { value: "BOG", label: "Bogotá (BOG), Colômbia" },
  { value: "MDE", label: "Medellín (MDE), Colômbia" },
  { value: "LIM", label: "Lima (LIM), Peru" },
  { value: "UIO", label: "Quito (UIO), Equador" },
  { value: "PTY", label: "Cidade do Panamá (PTY), Panamá" },
  { value: "SJO", label: "San José (SJO), Costa Rica" },
  { value: "MVD", label: "Montevidéu (MVD), Uruguai" },
  { value: "CCS", label: "Caracas (CCS), Venezuela" },

  // --- ASIA ---
  { value: "DXB", label: "Dubai (DXB), EAU" },
  { value: "AUH", label: "Abu Dhabi (AUH), EAU" },
  { value: "DOH", label: "Doha (DOH), Qatar" },
  { value: "SIN", label: "Singapura (SIN), Singapura" },
  { value: "BKK", label: "Banguecoque Suvarnabhumi (BKK), Tailândia" },
  { value: "HKG", label: "Hong Kong (HKG), Hong Kong" },
  { value: "NRT", label: "Tóquio Narita (NRT), Japão" },
  { value: "HND", label: "Tóquio Haneda (HND), Japão" },
  { value: "KIX", label: "Osaka Kansai (KIX), Japão" },
  { value: "ICN", label: "Seul Incheon (ICN), Coreia do Sul" },
  { value: "PEK", label: "Pequim Capital (PEK), China" },
  { value: "PKX", label: "Pequim Daxing (PKX), China" },
  { value: "PVG", label: "Xangai Pudong (PVG), China" },
  { value: "CAN", label: "Guangzhou (CAN), China" },
  { value: "DEL", label: "Nova Deli (DEL), Índia" },
  { value: "BOM", label: "Bombaim (BOM), Índia" },
  { value: "BLR", label: "Bangalore (BLR), Índia" },
  { value: "KUL", label: "Kuala Lumpur (KUL), Malásia" },
  { value: "CGK", label: "Jacarta (CGK), Indonésia" },
  { value: "DPS", label: "Bali Denpasar (DPS), Indonésia" },
  { value: "SGN", label: "Ho Chi Minh (SGN), Vietname" },
  { value: "HAN", label: "Hanói (HAN), Vietname" },
  { value: "MNL", label: "Manila (MNL), Filipinas" },
  { value: "TPE", label: "Taipé (TPE), Taiwan" },

  // --- AFRICA ---
  { value: "JNB", label: "Joanesburgo (JNB), África do Sul" },
  { value: "CPT", label: "Cidade do Cabo (CPT), África do Sul" },
  { value: "CAI", label: "Cairo (CAI), Egito" },
  { value: "CMN", label: "Casablanca (CMN), Marrocos" },
  { value: "RAK", label: "Marraquexe (RAK), Marrocos" },
  { value: "LAD", label: "Luanda (LAD), Angola" },
  { value: "MPM", label: "Maputo (MPM), Moçambique" },
  { value: "SID", label: "Ilha do Sal (SID), Cabo Verde" },
  { value: "RAI", label: "Praia (RAI), Cabo Verde" },
  { value: "VXE", label: "São Vicente (VXE), Cabo Verde" },
  { value: "DSS", label: "Dakar (DSS), Senegal" },
  { value: "ACC", label: "Acra (ACC), Gana" },
  { value: "LOS", label: "Lagos (LOS), Nigéria" },
  { value: "NBO", label: "Nairobi (NBO), Quénia" },
  { value: "ADD", label: "Adis Abeba (ADD), Etiópia" },
  { value: "ALG", label: "Argel (ALG), Argélia" },
  { value: "TUN", label: "Tunes (TUN), Tunísia" },
  { value: "TMS", label: "São Tomé (TMS), São Tomé e Príncipe" },
  { value: "OXB", label: "Bissau (OXB), Guiné-Bissau" },

  // --- OCEANIA ---
  { value: "SYD", label: "Sydney (SYD), Austrália" },
  { value: "MEL", label: "Melbourne (MEL), Austrália" },
  { value: "BNE", label: "Brisbane (BNE), Austrália" },
  { value: "PER", label: "Perth (PER), Austrália" },
  { value: "AKL", label: "Auckland (AKL), Nova Zelândia" },
  { value: "CHC", label: "Christchurch (CHC), Nova Zelândia" },
]
