export const MOCK_RESULTS = [
  {
    id: "1",
    type: "flight",
    carrier: "TAP Air Portugal",
    carrierLogo: "/tap.jpg",
    departureTime: "08:00",
    arrivalTime: "10:30",
    departureStation: "LIS",
    arrivalStation: "MAD",
    duration: "1h 30m",
    stops: 0,
    price: 85,
    currency: "EUR",
  },
  {
    id: "2",
    type: "train",
    carrier: "Renfe",
    carrierLogo: "/renfe.jpg",
    departureTime: "09:15",
    arrivalTime: "16:45",
    departureStation: "Lisboa - Santa Apolónia",
    arrivalStation: "Madrid - Atocha",
    duration: "6h 30m",
    stops: 1,
    price: 45,
    currency: "EUR",
  },
  {
    id: "3",
    type: "bus",
    carrier: "FlixBus",
    carrierLogo: "/flixbus.jpg",
    departureTime: "10:00",
    arrivalTime: "19:00",
    departureStation: "Lisboa Oriente",
    arrivalStation: "Madrid Estação Sur",
    duration: "8h 00m",
    stops: 0,
    price: 29,
    currency: "EUR",
  },
  {
    id: "4",
    type: "flight",
    carrier: "Iberia",
    carrierLogo: "/iberian-landscape.png",
    departureTime: "14:20",
    arrivalTime: "16:50",
    departureStation: "LIS",
    arrivalStation: "MAD",
    duration: "1h 30m",
    stops: 0,
    price: 92,
    currency: "EUR",
  },
  {
    id: "5",
    type: "train",
    carrier: "Comboios de Portugal",
    carrierLogo: "/abstract-geometric-shapes.png",
    departureTime: "21:30",
    arrivalTime: "07:00",
    departureStation: "Lisboa - Oriente",
    arrivalStation: "Madrid - Chamartín",
    duration: "8h 30m",
    stops: 0,
    price: 35,
    currency: "EUR",
    isOvernight: true,
  },
]
